import 'app_language.dart';

class AppLocalizations {
  final AppLanguage language;

  const AppLocalizations(this.language);

  static const Map<AppLanguage, Map<String, String>> _localizedValues = {
    AppLanguage.english: {
      'appName': 'Remindly',
      'lockScreenTitle': 'Security Unlock',
      'enterPin': 'Enter Security PIN',
      'biometricPrompt': 'Use Fingerprint / Face ID to unlock',
      'invalidPin': 'Invalid PIN code. Try again.',
      'memoriesTab': 'Memories',
      'searchTab': 'Search',
      'settingsTab': 'Settings',
      'aboutTab': 'About',
      'addMemoryTitle': 'Add Memory',
      'contentHint': 'What would you like to remember?\ne.g. "The spare key is inside the blue cupboard."',
      'categoryLabel': 'Category',
      'tagsLabel': 'Tags',
      'reminderLabel': 'Reminder (Optional)',
      'setReminder': 'Set Reminder Date & Time',
      'securityLabel': 'Security & Privacy',
      'markSecure': 'Mark as Secure / Private 🔒',
      'securitySubtitle': 'Protects this memory requiring security unlock',
      'saveMemory': 'Confirm & Save Memory',
      'memorySaved': 'Memory saved successfully!',
      'searchHint': 'Search memories, tags, category...',
      'tapToSpeak': 'Tap to speak',
      'listening': 'Listening...',
      'languageSetting': 'Language',
      'selectLanguage': 'Select App Language',
      'aboutTitle': 'About Remindly',
      'appDescription': 'Smart personal memory & reminder assistant application.',
      'developerCredit': 'Developed by Vijay Sankar S',
      'readoutToggle': 'Read search results aloud (Voice Readout)',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'confirmDelete': 'Delete Memory?',
      'confirmDeleteMsg': 'Are you sure you want to delete this memory? This action cannot be undone.',
      'noMemories': 'No memories saved yet.',
      'noSearchResults': 'No matching memories found.',
      'sourceVoice': 'Recorded via Voice',
      'sourceText': 'Typed Text',
      'memoryDetail': 'Memory Detail',
      'created': 'Created',
      'lastUpdated': 'Last Updated',
      'scheduledReminder': 'Reminder Scheduled',
      'secureBadge': 'Secure',
    },
    AppLanguage.tamil: {
      'appName': 'Remindly',
      'lockScreenTitle': 'பாதுகாப்பு பூட்டு',
      'enterPin': 'பாதுகாப்பு PIN ஐ உள்ளிடவும்',
      'biometricPrompt': 'கைரேகை / முக அங்கீகாரத்தைப் பயன்படுத்தவும்',
      'invalidPin': 'தவறான PIN. மீண்டும் முயற்சிக்கவும்.',
      'memoriesTab': 'நினைவுகள்',
      'searchTab': 'தேடல்',
      'settingsTab': 'அமைப்புகள்',
      'aboutTab': 'பற்றி',
      'addMemoryTitle': 'நினைவைச் சேர்',
      'contentHint': 'எதை நினைவில் கொள்ள விரும்புகிறீர்கள்?\nஎ.கா. "நீல அலமாரியில் சாவி உள்ளது."',
      'categoryLabel': 'வகை',
      'tagsLabel': 'குறிச்சொற்கள்',
      'reminderLabel': 'நினைவூட்டல் (விருப்பத்தேர்வு)',
      'setReminder': 'தேதி & நேரத்தை அமைக்கவும்',
      'securityLabel': 'பாதுகாப்பு மற்றும் தனியுரிமை',
      'markSecure': 'பாதுகாப்பானது / தனியார் 🔒',
      'securitySubtitle': 'பாதுகாப்பு பூட்டுடன் இந்த நினைவைப் பாதுகாக்கிறது',
      'saveMemory': 'உறுதிசெய்து சேமிக்கவும்',
      'memorySaved': 'நினைவு வெற்றிகரமாக சேமிக்கப்பட்டது!',
      'searchHint': 'நினைவுகள், குறிச்சொற்கள் தேட...',
      'tapToSpeak': 'பேச தட்டவும்',
      'listening': 'கேட்கிறது...',
      'languageSetting': 'மொழி (Language)',
      'selectLanguage': 'பயன்பாட்டு மொழியைத் தேர்ந்தெடுக்கவும்',
      'aboutTitle': 'Remindly பற்றி',
      'appDescription': 'புத்திசாலித்தனமான தனிப்பட்ட நினைவு உதவியாளர் பயன்பாடு.',
      'developerCredit': 'விஜய் சங்கர் எஸ் உருவாக்கியது',
      'readoutToggle': 'தேடல் முடிவுகளை குரலில் படியுங்கள்',
      'cancel': 'ரத்துசெய்',
      'delete': 'நீக்கு',
      'confirmDelete': 'நினைவை நீக்க வேண்டுமா?',
      'confirmDeleteMsg': 'இந்த நினைவை நீக்க விரும்புகிறீர்களா? இதை மீட்டெடுக்க முடியாது.',
      'noMemories': 'இன்னும் நினைவுகள் சேமிக்கப்படவில்லை.',
      'noSearchResults': 'நினைவுகள் எதுவும் கிடைக்கவில்லை.',
      'sourceVoice': 'குரல் மூலம் பதிவு செய்யப்பட்டது',
      'sourceText': 'எழுதப்பட்ட உரை',
      'memoryDetail': 'நினைவு விவரம்',
      'created': 'உருவாக்கப்பட்டது',
      'lastUpdated': 'கடைசியாக புதுப்பிக்கப்பட்டது',
      'scheduledReminder': 'திட்டமிடப்பட்ட நினைவூட்டல்',
      'secureBadge': 'பாதுகாப்பானது',
    },
    AppLanguage.kannada: {
      'appName': 'Remindly',
      'lockScreenTitle': 'ಭದ್ರತಾ ಲಾಕ್',
      'enterPin': 'ಸುರಕ್ಷತಾ PIN ನಮೂದಿಸಿ',
      'biometricPrompt': 'ಅನ್ಲಾಕ್ ಮಾಡಲು ಬೆರಳಚ್ಚು ಬಳಸಿ',
      'invalidPin': 'ಅಮಾನ್ಯವಾದ PIN. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
      'memoriesTab': 'ನೆನಪುಗಳು',
      'searchTab': 'ಹುಡುಕಾಟ',
      'settingsTab': 'ಸಂಯೋಜನೆಗಳು',
      'aboutTab': 'ಕುರಿತು',
      'addMemoryTitle': 'ನೆನಪನ್ನು ಸೇರಿಸಿ',
      'contentHint': 'ನೀವು ಏನನ್ನು ನೆನಪಿಟ್ಟುಕೊಳ್ಳಲು ಬಯಸುತ್ತೀರಿ?\nಉದಾ: "ಬಿಳಿ ಕಪಾಟಿನಲ್ಲಿ ಕೀಲಿ ಇದೆ."',
      'categoryLabel': 'ವರ್ಗ',
      'tagsLabel': 'ಟ್ಯಾಗ್ಗಳು',
      'reminderLabel': 'ಜ್ಞಾಪನೆ (ಐಚ್ಛಿಕ)',
      'setReminder': 'ಜ್ಞಾಪನೆ ದಿನಾಂಕ ಮತ್ತು ಸಮಯವನ್ನು ಹೊಂದಿಸಿ',
      'securityLabel': 'ಭದ್ರತೆ ಮತ್ತು ಗೌಪ್ಯತೆ',
      'markSecure': 'ಸುರಕ್ಷಿತ / ಖಾಸಗಿ ಎಂದು ಗುರುತಿಸಿ 🔒',
      'securitySubtitle': 'ಭದ್ರತಾ ಲಾಕ್ ಮೂಲಕ ಈ ನೆನಪನ್ನು ಸಂರಕ್ಷಿಸುತ್ತದೆ',
      'saveMemory': 'ಖಚಿತಪಡಿಸಿ ಮತ್ತು ನೆನಪನ್ನು ಉಳಿಸಿ',
      'memorySaved': 'ನೆನಪು ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ!',
      'searchHint': 'ನೆನಪುಗಳು, ಟ್ಯಾಗ್‌ಗಳನ್ನು ಹುಡುಕಿ...',
      'tapToSpeak': 'ಮಾತನಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
      'listening': 'ಕೇಳುತ್ತಿರುವುದು...',
      'languageSetting': 'ಭಾಷೆ (Language)',
      'selectLanguage': 'ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'aboutTitle': 'Remindly ಕುರಿತು',
      'appDescription': 'ಬುದ್ಧಿವಂತ ವೈಯಕ್ತಿಕ ನೆನಪು ಮತ್ತು ಜ್ಞಾಪನೆ ಸಹಾಯಕ ಅಪ್ಲಿಕೇಶನ್.',
      'developerCredit': 'ವಿಜಯ್ ಶಂಕರ್ ಎಸ್ ಅವರಿಂದ ಅಭಿವೃದ್ಧಿಪಡಿಸಲಾಗಿದೆ',
      'readoutToggle': 'ಹುಡುಕಾಟ ಫಲಿತಾಂಶಗಳನ್ನು ಗಟ್ಟಿಯಾಗಿ ಓದಿ',
      'cancel': 'ರದ್ದುಗೊಳಿಸಿ',
      'delete': 'ಅಳಿಸಿ',
      'confirmDelete': 'ನೆನಪನ್ನು ಅಳಿಸಬೇಕೇ?',
      'confirmDeleteMsg': 'ನೀವು ಖಂಡಿತವಾಗಿಯೂ ಈ ನೆನಪನ್ನು ಅಳಿಸಲು ಬಯಸುತ್ತೀರಾ?',
      'noMemories': 'ಇನ್ನೂ ಯಾವುದೇ ನೆನಪುಗಳನ್ನು ಉಳಿಸಲಾಗಿಲ್ಲ.',
      'noSearchResults': 'ಯಾವುದೇ ನೆನಪುಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
      'sourceVoice': 'ಧ್ವನಿಯ ಮೂಲಕ ರೆಕಾರ್ಡ್ ಮಾಡಲಾಗಿದೆ',
      'sourceText': 'ಬರೆದ ಪಠ್ಯ',
      'memoryDetail': 'ನೆನಪಿನ ವಿವರಣೆ',
      'created': 'ಸೃಷ್ಟಿಸಿದ ದಿನಾಂಕ',
      'lastUpdated': 'ಕೊನೆಯದಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ',
      'scheduledReminder': 'ನಿಗದಿತ ಜ್ಞಾಪನೆ',
      'secureBadge': 'ಸುರಕ್ಷಿತ',
    },
    AppLanguage.tulu: {
      'appName': 'Remindly',
      'lockScreenTitle': 'ರಕ್ಷಣೆ ಲಾಕ್',
      'enterPin': 'ಸುರಕ್ಷತಾ PIN ನಮೂದು ಮಲ್ಪುಲೆ',
      'biometricPrompt': 'ಅನ್ಲಾಕ್ ಮಲ್ಪೆರೆ ಬೆರಳು ಗುರುತು ಬಳಸುಲೆ',
      'invalidPin': 'ತಪ್ಪು PIN. ಮೆಯಿತ್ ಪ್ರಯತ್ನ ಮಲ್ಪುಲೆ.',
      'memoriesTab': 'ನೆನಪುಲು',
      'searchTab': 'ನಾಡೋನು',
      'settingsTab': 'ಸೆಟ್ಟಿಂಗ್ಸ್',
      'aboutTab': 'ಬಗ್ಗೆ',
      'addMemoryTitle': 'ನೆನಪು ಸೇರಸಾಲೆ',
      'contentHint': 'ಈರ್ ದಾನೆ ನೆನಪು ದೀವೊಡು ಅಂದ್ ಎನ್ನೊಂದುಲ್ಲರ್?\nಉದಾ: "ಚೀಪೆ ಕಪಾಟುಡು ಕೀ ಉಂಡು."',
      'categoryLabel': 'ವರ್ಗ',
      'tagsLabel': 'ಟ್ಯಾಗ್ಲು',
      'reminderLabel': 'ಜ್ಞಾಪನೆ (ಐಚ್ಛಿಕ)',
      'setReminder': 'ಜ್ಞಾಪನೆ ದಿನಾಂಕ ಬೊಕ್ಕ ಪೊರ್ತು ದೀಲೆ',
      'securityLabel': 'ಭದ್ರತೆ ಬೊಕ್ಕ ಗೌಪ್ಯತೆ',
      'markSecure': 'ರಕ್ಷಣೆ / ಖಾಸಗಿ ಅಂದ್ ದೀಲೆ 🔒',
      'securitySubtitle': 'ರಕ್ಷಣೆ ಲಾಕ್ ಮೂಲಕ ಈ ನೆನಪುನ್ ಕಾಪುಂಡು',
      'saveMemory': 'ಖಚಿತ ಮಲ್ತ್ ನೆನಪು ಒರಿಪಾಲೆ',
      'memorySaved': 'ನೆನಪು ಯಶಸ್ವಿಯಾದ್ ಒರಿಪಾಯರ್!',
      'searchHint': 'ನೆನಪುಲು, ಟ್ಯಾಗ್‌ಗಳನ್ನು ನಾಡ್ಲೆ...',
      'tapToSpeak': 'ಪಾತೆರರೆ ಒತ್ತುಲೆ',
      'listening': 'ಕೇನೊಂದುಂಡು...',
      'languageSetting': 'ಭಾಷೆ (Language)',
      'selectLanguage': 'ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆ ಆಯ್ಕೆ ಮಲ್ಪುಲೆ',
      'aboutTitle': 'Remindly ಬಗ್ಗೆ',
      'appDescription': 'ಸ್ಮಾರ್ಟ್ ವೈಯಕ್ತಿಕ ನೆನಪು ಬೊಕ್ಕ ಜ್ಞಾಪನೆ ಸಹಾಯಕ ಅಪ್ಲಿಕೇಶನ್.',
      'developerCredit': 'ವಿಜಯ್ ಶಂಕರ್ ಎಸ್ ಆರ್ ಸೃಷ್ಟಿ ಮಲ್ತಿನಿ',
      'readoutToggle': 'ನಾಡಿನ ಫಲಿತಾಂಶನ್ ಗಟ್ಟಿಯಾದ್ ಓದುಲೆ',
      'cancel': 'ರದ್ದು ಮಲ್ಪುಲೆ',
      'delete': 'ದೆತ್ತ್ ಪಾಡ್ಲೆ',
      'confirmDelete': 'ನೆನಪು ದೆತ್ತ್ ಪಾಡೊಡಾ?',
      'confirmDeleteMsg': 'ಈರ್ ನಿಜವಾದ್ಲಾ ಈ ನೆನಪುನ್ ದೆತ್ತ್ ಪಾಡೆರೆ ಉಲ್ಲರಾ?',
      'noMemories': 'ನನಲಾ ಒವ್ವೆ ನೆನಪು ಒರಿಪಾಡೆಜಿ.',
      'noSearchResults': 'ಒವ್ವೆ ನೆನಪುಲು ತಿಕ್ಕಿಜಿ.',
      'sourceVoice': 'ಸ್ವರೊಟು ರೆಕಾರ್ಡ್ ಮಲ್ತಿನಿ',
      'sourceText': 'ಬರೆತಿನಿ',
      'memoryDetail': 'ನೆನಪುದ ವಿವರ',
      'created': 'ಮಲ್ತಿನಿ ದಿನ',
      'lastUpdated': 'ಕಡೆಕ್ ಬದಲಾವಣೆ ಮಲ್ತಿನಿ',
      'scheduledReminder': 'ದೀನ ಜ್ಞಾಪನೆ',
      'secureBadge': 'ರಕ್ಷಣೆ',
    },
  };

  String get(String key) {
    return _localizedValues[language]?[key] ??
        _localizedValues[AppLanguage.english]?[key] ??
        key;
  }
}
